### ISSUE TITLE
3xx Unit Tests Failing

### ISSUE THREAD

**Issue by jcznder** [VerticalResearchGroup/miaow#18]
Hi there,

Not sure if I am missing something, but I followed the Bringup and Verification wiki and seem to be failing the 3xx unit tests and the benchmark tests.
Specifically:
`test_300_tbuff_ld_fmt_x
test_301_tbuff_ld_fmt_xyzw
test_302_tbuff_st_fmt_x
test_303_tbuff_st_fmt_xyzw
test_304_ds_wr_b32
test_305_ds_rd_b32`
The values are either wrong, or in the latter cases, the test hangs. The MTBUF and GDS instructions seem to be the culprits.

Any advice on what I could be doing wrong? Thanks!

**Comment by zwabbit** [comment]
There are several vector memory load operations that are outright broken in the current iteration. At present I'm assigned to different projects and have not had any time to fix any of them, not least because what those instructions are "officially" supposed to do is kind of murky. The entire memory interface ultimately needs to be overhauled, which again, I am not in a position to do due to other project commitments.

**Comment by jcznder** [comment]
Okay, thanks! Just making sure this is expected behavior.

**Comment by Remdon** [comment]
@jh46537 Did you happen to work on this issue? @zwabbit I would like to help if I can. This is a neat project I think should get more attention.

**Comment by jcznder** [comment]
@Remdon Nope, I have done no work on this. We decided to go in a different direction for our project. I'd be happy to see active development on this project though. =)

Also closing this issue as I should have done 3 years ago.
