### ISSUE TITLE
Why not ask to AMD to merge your awesome work on polaris/polaris next ? 

### ISSUE THREAD

**Issue by LifeIsStrange** [VerticalResearchGroup/miaow#9]
Polaris is the name for the upcoming GCN 2.0 *

**Comment by LifeIsStrange** [comment]
I don't understund why you keep my issue open but don't answer me, you wait that the project become more featurefull ?

**Comment by zwabbit** [comment]
MIAOW is based off of the GCN 1.0 specification, the first generation of GCN. AMD is now on the fourth generation. By all rights AMD is well ahead of anything that we have achieved and they have a much more complete implementation in the first place. There's nothing for us to ask them to include since their own work is far ahead of what we have.

**Comment by LifeIsStrange** [comment]
Thank you for your answer and for making opensource :)
